name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          region: ap-south-1  

      - name: Build and Push Docker image
        run: |
          docker build -t hello-world-nodeapp .
          docker tag hello-world-nodeapp:latest ${{ steps.login-ecr.outputs.registry }}/hello-world-nodeapp:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/hello-world-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: hello-world-service
          cluster: hello-world-cluster
          wait-for-service-stability: true
