name: Deploy to AWS ECS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
<<<<<<< HEAD
          region: ap-south-1  # Specify your AWS region here
=======
          region: ap-south-1  
>>>>>>> 0abfca353e24e90d2d82303c741ce8f87f6c5807

      - name: Build and Push Docker image
        env:
          AWS_REGION: ap-south-1  # Set AWS region as an environment variable
        run: |
          docker build -t hello-world-app .
          docker tag hello-world-app:latest ${{ steps.login-ecr.outputs.registry }}/hello-world-app:latest
          docker push ${{ steps.login-ecr.outputs.registry }}/hello-world-app:latest

      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: task-definition.json
          service: hello-world-service
          cluster: hello-world-cluster
          wait-for-service-stability: true
        env:
          AWS_REGION: ap-south-1  # Set AWS region as an environment variable
